# ~/.bash_profile or ~/.profile    #The personal initialization file, executed for login shells
# ~/.bashrc                        #The individual per-interactive-shell startup file
# ~/.bash_logout		   #The individual login shell cleanup file, executed when a login shell exits
# ~/.inputrc                       #Individual readline initialization file

# The latest version as installed by the Cygwin Setup program can
# always be found at /etc/defaults/etc/bash.bash_logout
