# Check that we haven't already been sourced.
[[ -z ${HOME_INCLUDE_ZSHENV} ]] && { export HOME_INCLUDE_ORDER="$(/bin/expr ${HOME_INCLUDE_ORDER} + 1)"; export HOME_INCLUDE_ZSHENV="${HOME_INCLUDE_ORDER}"; } || return

[[ -e "${HOME}/.environment" ]] && source "${HOME}/.environment"
